src/LoggingMvc.App/ViewModels/ErrorViewModel.cs
namespace LoggingMvc.App.ViewModels
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/LoggingMvc.App/ViewModels/LogViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace LoggingMvc.App.ViewModels
{
    public class LogViewModel
    {
        [Key]
        public Guid Id { get; set; }
        [Required]
        public DateTime Date { get; set; } = DateTime.Now;
        [Required]
        public string Type { get; set; }
        [Required]
        public string Description { get; set; }
    }
}

src/LoggingMvc.App/Controllers/BaseController.cs
using LoggingMvc.Business.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace LoggingMvc.App.Controllers
{
    public class BaseController : Controller
    {
        private readonly INotifier _notifier;

        public BaseController(INotifier notifier)
        {
            _notifier = notifier;
        }

        protected bool IsValid()
        {
           return !_notifier.HasNotifications();
        }
    }
}

src/LoggingMvc.App/Controllers/HomeController.cs
using LoggingMvc.App.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LoggingMvc.App.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/LoggingMvc.App/Controllers/LogController.cs
using AutoMapper;
using LoggingMvc.App.Utils;
using LoggingMvc.App.ViewModels;
using LoggingMvc.Business.Interfaces;
using LoggingMvc.Business.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LoggingMvc.App.Controllers
{
    public class LogController : BaseController
    {
        private readonly ILogService _logService;
        private readonly IMapper _mapper;

        public LogController(IMapper mapper, 
                             ILogService logService,
                             INotifier notifier) : base(notifier)
        {
            _mapper = mapper;
            _logService = logService;
        }

        [Route("logs")]
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            await Audit("Page Index");

            ViewData["CurrentSort"] = sortOrder;
            ViewData["DateSortParam"] = String.IsNullOrEmpty(sortOrder) ? "date" : "";
            ViewData["LogTypeSortParam"] = String.IsNullOrEmpty(sortOrder) ? "logType_desc" : "";
            ViewData["DescriptionSortParam"] = String.IsNullOrEmpty(sortOrder) ? "description_desc" : "";

            if (searchString != null)
                pageNumber = 1;
            else
                searchString = currentFilter;

            ViewData["CurrentFilter"] = searchString;

            var logs = _mapper.Map<IEnumerable<LogViewModel>>(await _logService.GetAll());

            if (!String.IsNullOrEmpty(searchString))
                logs = await Search(logs, searchString);
            else
                logs = await ListSortOrder(logs, sortOrder);

            int pageSize = 10;

            return View(await PaginatedList<LogViewModel>.CreateAsync(logs, pageNumber ?? 1, pageSize));
        }

        [Route("log/{id:guid}")]
        public async Task<IActionResult> Details(Guid id)
        {
            var logViewModel = await GetLogById(id);

            if (logViewModel == null)
            {
                return NotFound();
            }

            await Audit("Page Details");

            return View(logViewModel);
        }

        [Route("new-log")]
        public IActionResult Create()
        {
            ViewBag.LogType = LogType();
            return View();
        }

        [HttpPost]
        [Route("new-log")]
        public async Task<IActionResult> Create([Bind("Id, Date, Type, Description")] LogViewModel logViewModel)
        {
            if (!ModelState.IsValid) return View(logViewModel);

            var log = _mapper.Map<Log>(logViewModel);
            await _logService.Add(log);

            if (!IsValid()) return View(logViewModel);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [Route("log")]
        public async Task<IActionResult> CreateFromWebServices([FromBody] LogViewModel logViewModel)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var log = _mapper.Map<Log>(logViewModel);
            await _logService.Add(log);

            if (!IsValid()) return BadRequest(logViewModel);

            return Ok(log);
        }

        [Route("edit-log/{id:guid}")]
        public async Task<IActionResult> Edit(Guid id)
        {
            ViewBag.LogType = LogType();
            var logViewModel = await GetLogById(id);

            if (logViewModel == null)
                return NotFound();

            return View(logViewModel);
        }

        [HttpPost]
        [Route("edit-log/{id:guid}")]
        public async Task<IActionResult> Edit(Guid id, LogViewModel logViewModel)
        {
            if (id != logViewModel.Id) return NotFound();

            if (!ModelState.IsValid) return View(logViewModel);

            var log = _mapper.Map<Log>(logViewModel);
            await _logService.Update(log);

            if (!IsValid()) return View(await GetLogById(id));

            return RedirectToAction("Index");
        }

        private async Task<LogViewModel> GetLogById(Guid id)
        {
            return _mapper.Map<LogViewModel>(await _logService.GetById(id));
        }

        private List<SelectListItem> LogType()
        {
            List<SelectListItem> logs = new()
            {
                new SelectListItem { Value = "Error", Text = "Error"},
                new SelectListItem { Value = "Info", Text = "Info"},
                new SelectListItem { Value = "Warn", Text = "Warn"}
            };

            return logs;
        }

        private async Task<IEnumerable<LogViewModel>> ListSortOrder(IEnumerable<LogViewModel> logs, string sortOrder)
        {
            return logs = sortOrder switch
            {
                "date" => logs.OrderBy(l => l.Date),
                "logType_desc" => logs.OrderByDescending(l => l.Type),
                "description_desc" => logs.OrderByDescending(l => l.Description),
                _ => logs.OrderByDescending(l => l.Date),
            };
        }

        private async Task<IEnumerable<LogViewModel>> Search(IEnumerable<LogViewModel> logs, string search)
            => logs.Where(l => l.Type.ToLower().Contains(search.ToLower()) || l.Description.ToLower().Contains(search.ToLower()));
        private async Task Audit(string message)
        {
            ModelState.Clear();
            var newLog = new LogViewModel { Type = "Info", Description = $"{message}" };
            await Create(newLog);
        }
    }
}

src/LoggingMvc.App/Extensions/SummaryViewComponent.cs
using LoggingMvc.Business.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace LoggingMvc.App.Extensions
{
    public class SummaryViewComponent : ViewComponent
    {
        private readonly INotifier _notifier;

        public SummaryViewComponent(INotifier notifier)
        {
            _notifier = notifier;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notificacoes = await Task.FromResult(_notifier.GetNotifications());
            notificacoes.ForEach(c => ViewData.ModelState.AddModelError(string.Empty, c.Message));

            return View();
        }
    }
}

src/LoggingMvc.App/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Teste técnico - Agap2it</h1>
    <p>Filipe Henrique Gomes da Silva</p>
</div>

src/LoggingMvc.App/Views/Log/Create.cshtml
@model LoggingMvc.App.ViewModels.LogViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create Log</h1>


<a asp-action="Index" class="btn btn-secondary">Back</a>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">

            <vc:Summary></vc:Summary>

            <div class="form-group m-2">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" class="form-control" asp-items="@ViewBag.LogType"></select>             
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group m-2">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group m-2">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/LoggingMvc.App/Views/Log/Details.cshtml
@model LoggingMvc.App.ViewModels.LogViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <a asp-action="Index" class="btn btn-secondary">Back</a>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-primary">Edit</a>     
</div>

src/LoggingMvc.App/Views/Log/Edit.cshtml
@model LoggingMvc.App.ViewModels.LogViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<a asp-action="Index" class="btn btn-secondary">Back</a>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group m-2">
                <label asp-for="Type" class="control-label"></label>
                 <select asp-for="Type" class="form-control" asp-items="@ViewBag.LogType">
                </select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group m-2">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group m-2">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/LoggingMvc.App/Views/Log/Index.cshtml
@using LoggingMvc.App.Utils
@model PaginatedList<LoggingMvc.App.ViewModels.LogViewModel>

@{
    ViewData["Title"] = "Logs";
}

<h1>@ViewData["Title"]</h1>

<p>
    <a class="btn btn-primary" asp-action="Create">Add Log</a>
</p>

<form asp-action="Index" method="get">
    <div class="row mb-3">
        <label class="">Find by Log Type or Description:</label>
        <div class="col-4">
            <input type="text" class="form-control" name="SearchString" value="@ViewData["CurrentFilter"]" />
        </div>
        <div class="col-4">
            <input type="submit" value="Search" class="btn btn-primary" />
            <a asp-action="Index" class="btn btn-secondary">Clear</a>
        </div>
    </div>
</form>


<table class="table table-hover">
    <thead class="table-secondary">
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["DateSortParam"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">
                    Date
                </a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["LogTypeSortParam"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">
                    Type
                </a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["DescriptionSortParam"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">
                    Description
                </a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td class="text-right">
                    <a class="btn btn-info" asp-action="Details" asp-route-id="@item.Id"><spam class="fa fa-search"></spam></a>
                    <a class="btn btn-warning" asp-action="Edit" asp-route-id="@item.Id"><spam class="fa fa-pencil-alt"></spam></a>
                </td>
            </tr>
        }
    </tbody>
</table>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-light @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-light @nextDisabled">
    Next
</a>

src/LoggingMvc.App/Views/Shared/Components/Summary/Default.cshtml
@if (ViewData.ModelState.ErrorCount > 0)
{
    <div style="padding-top: 15px;"></div>

    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h3 id="returnMessage" style="padding-top: 20px">Oops! Something went wrong :(</h3>
        <div style="padding-top: 20px" asp-validation-summary="ModelOnly" class="text-danger"></div>
    </div>
}

@if (!string.IsNullOrEmpty(ViewBag.Sucess))
{
    <div style="padding-top: 15px"></div>

    <div id="msg_box" class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h3 id="returnMessage">@ViewBag.Sucesso</h3>
    </div>
}

@if (TempData["Sucess"] != null)
{
    <div style="padding-top: 15px"></div>

    <div id="msg_box" class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h4 id="returnMessage">@Html.Raw(TempData["Sucess"].ToString())</h4>
    </div>
}

src/LoggingMvc.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LoggingMvc - Agap2it</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LoggingMvc.App.styles.css" asp-append-version="true" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LoggingMvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Log" asp-action="Index">Logs</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - LoggingMvc - Agap2it - Filipe Henrique Gomes da Silva
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>